FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app app
COPY db db
COPY worker worker
COPY configs configs

CMD ["python", "-m", "worker.main"]
