services:
  transaction-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-engine
    command: python -m app.main --count 10000 --output output
    volumes:
      - type: bind
        source: ./output
        target: /app/output

  transaction-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: transaction-api
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./output
        target: /app/output

  transaction-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-dashboard
    command: streamlit run app/dashboard.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: ./output
        target: /app/output
    depends_on:
      transaction-engine:
        condition: service_completed_successfully