from prometheus_client import Counter, Gauge, Histogram


TRANSACTIONS_INGESTED_TOTAL = Counter(
    "transactions_ingested_total",
    "Total number of transactions received by the API.",
    ["endpoint"],
)

TRANSACTIONS_QUEUED_TOTAL = Counter(
    "transactions_queued_total",
    "Total number of transactions pushed into the queue.",
    ["queue_name"],
)

QUEUE_DEPTH = Gauge(
    "transaction_queue_depth",
    "Current number of messages waiting in the transaction queue.",
    ["queue_name"],
)

TRANSACTIONS_PROCESSED_TOTAL = Counter(
    "transactions_processed_total",
    "Total number of transactions processed by the worker.",
)

ALERTS_GENERATED_TOTAL = Counter(
    "alerts_generated_total",
    "Total number of alerts generated by the worker.",
    ["alert_category"],
)

RULE_MATCHES_TOTAL = Counter(
    "rule_matches_total",
    "Total number of matched anomaly rules.",
    ["rule_code", "category"],
)

WORKER_PROCESSING_LATENCY_SECONDS = Histogram(
    "worker_processing_latency_seconds",
    "Time spent processing one transaction in the worker.",
)

WORKER_ERRORS_TOTAL = Counter(
    "worker_errors_total",
    "Total number of worker processing errors.",
)

ML_TRAINED_STATUS = Gauge(
    "ml_trained_status",
    "Whether the ML anomaly model is trained. 1 means trained, 0 means not trained.",
)
